version: "3.5"

services:
  api01: &api
    image: guilhermeabel8/rinha-q1-go-api:latest
    hostname: api01
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "60MB"
  api02:
    <<: *api 
    hostname: api02
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "70MB"
  db:
    image: postgres:alpine
    hostname: db
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=db
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.config_file
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.config_file
    deploy:
      resources:
        limits:
          cpus: "0.85"
          memory: "310MB"


