version: '3.5'
services:
  postgres:
    image: postgres:latest
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_financial
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c max_connections=200 -c shared_buffers=100MB
    network_mode: host
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    expose:
      - "5432"
    deploy:
      resources:
        limits:
          cpus: '0.70'
          memory: 196MB

  api01: &api
    image: thalessantanna/app_rinha_2024_go:latest
    hostname: api01
    container_name: api01
    environment:
      - PORT=30001
      - DB_HOSTNAME=localhost
      - POOL_MAX=10
      - POOL_MIN=5
    network_mode: host
    expose:
      - "30001"
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 64MB

  api02:
    <<: *api
    hostname: api02
    container_name: api02
    environment:
      - PORT=30002
      - DB_HOSTNAME=localhost
      - POOL_MAX=10
      - POOL_MIN=5
    expose:
      - "30002"

  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    expose:
      - "9999"
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: 128MB
